export const sections = [
  {
    id: 1,
    title: "Mundo VIP",
    subtitle: "Contenido exclusivo",
    path: "/premium",
    image: "/fabulosa_premiun.webp",
    badge: "VIP",
  },
  {
    id: 2,
    title: "Noticias",
    subtitle: "PSC Informa",
    path: "https://psc-informa.vercel.app",
    external: true,
    image: "/psc_imforma.webp",
    badge: "NEWS",
  },
  {
    id: 3,
    title: "Fabulosa Tube",
    subtitle: "Videos",
    path: "/fabulosa-tube",
    image: "/fabulosa_play.webp",
  },
  {
    id: 4,
    title: "Fabulosito Kids",
    subtitle: "Niños",
    path: "/tv",
    image: "/fabulosito_kids.webp",
  },
  {
    id: 5,
    title: "Borrachos Play",
    subtitle: "Música",
    path: "/ranchera",
    image: "/borrachos_play.webp",
  },
  {
    id: 6,
    title: "Radios CR",
    subtitle: "En vivo",
    path: "/radios-cr",
    image: "/card-radios.webp",
    badgeLive: true,
  },
  {
    id: 7,
    title: "Cine Play",
    subtitle: "Películas",
    path: "/cine-play",
    image: "/cine_play.png",
  },
  {
    id: 8,
    title: "Canales Play",
    subtitle: "TV en vivo",
    path: "/canales-play",
    image: "/canales_play.png",
    badgeLive: true,
  },
  {
    id: 9,
    title: "Karaoke",
    subtitle: "Canta",
    path: "/karaoke",
    image: "/card-fabulosa-karaoke.webp",
  },
  {
    id: 10,
    title: "Alabanza",
    subtitle: "Cristiano",
    path: "/alabanza",
    image: "/card-alabanza.webp",
  },
  {
    id: 11,
    title: "Cámaras",
    subtitle: "En vivo",
    path: "/camaras",
    image: "/card-camaras.webp",
  },
  {
    id: 12,
    title: "Mercadeo",
    subtitle: "Negocios",
    path: "/centro-mercadeo",
    image: "/mercadeo.webp",
  }
];